### ISSUE TITLE
Talent tree

### ISSUE THREAD

**Issue by Vasago** [Takenbacon/wowarmory#2] opened 2013-01-17 04:25 UTC
In many web browsers talent tree is not shown properly or even any of the talents also positioning is very bad for example in Mozilla Firefox.

**Comment by Takenbacon** [comment] 2013-01-17 05:58
I have the fix for this on my private repo, the problem is i bundled it with a huge cleanup so it's extremely hard to tell what all i changed (Deeply regretting that now) D: I'll just commit my fix for chrome for now, then when i come back ill work on fixing firefox.

**Closed as completed** 2013-01-18 00:28 UTC
Labels: Javascript
